apiVersion: v1
kind: Pod
metadata:
  name: flask-ui-pod
  labels:
    app: flask-ui
    tier: ui
spec:
  containers:
    - name: flask-ui
      image: flask-ui-docker:v1
      ports:
        - containerPort: 8080
