version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "dummy-host-data"
      LDAP_DOMAIN: "dummy-host.com"
      LDAP_BASE_DN: "dc=dummy-host,dc=com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_CONFIG_PASSWORD: "admin"
      LDAP_TLS: "true"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
    command: /bin/bash /init/add_users.sh
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./init:/init
    networks:
      - dummy-ldap

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
    depends_on:
      - openldap
    ports:
      - "8000:80"
    networks:
      - dummy-ldap

networks:
  dummy-ldap:
    driver: bridge
